# This file stores all constant values.

PATH = {
    "weakly_supervised": {
        "path": "data/reports/"
    },
    "RAG": {
        "prev_retrieved": "outputs/retrieved/",
        "post_retrieved": "outputs/postRAG/Llama-3.1-70B-Instruct/"
    },
    "LLM": {
        "examples": "data/few_shot_examples.json"
    },
    "TAX": "data/ifrs_sds_taxonomy.json",
    "KG": "outputs/graph/"
}

LABELS_DICT = {
    "entities": [
        "organization",
        "sustainability report",
        "business model",
        "governance",
        "strategy",
        "risk",
        "opportunity",
        "target",
        "disclosure standard",
        "disclosure topic"
    ],
    "relations": [
        "ComparedTo",
        "Outputs",
        "RunBy",
        "ProvidedBy",
        "ValidatedBy",
        "UsedIn",
        "MeasuredAt",
        "MountedOn",
        "TargetsLocation",
    ],
    "label_mapper": {
        "Organizations": "organization",
        "Sustainability reports": "sustainability report",
        "Disclosure report": "sustainability report",
        "Climate disclosure report": "sustainability report",
        "Financial report": "sustainability report",
        "GOVERNANCE": "governance",
        "STRATEGY": "strategy",
        "Climate risks": "risk",
        "RISKS": "risk",
        "Climate opportunity": "opportunity",
        "OPPORTUNITY": "opportunity",
        "Climate targets": "target",
        "Climate goals": "target",
        "Sustainability targets": "target",
        "Sustainability goals": "target",
        "METRICS AND TARGETS": "target",
        "Reporting standard": "disclosure standard",
        "Reporting topic": "disclosure topic"
    },
}
text_template = "<heading>{}</heading>\n{}\n"

REPORTS = [
    "2022 Microsoft Environmental Sustainability Report",
    "2022_BXP_ESG_Report",
    "2023 Lloyds sustainability report",
    "AEO 2022 ESG Report",
    "AstraZeneca Sustainability Report 2023",
    "AT&T 2022 Sustainability Summary",
    "Boeing 2023 Sustainability Report",
    "CostCo Climate Action Plan",
    "Coca-Cola Business Sustainability Report 2022",
    "CT REIT 2022 ESG Report",
    "Deloitte 2023 Global Impact Report",
    "HM Group Sustainability Disclosure 2022",
    "HSBC Annual Holdings and Accounts Report 2023",
    "JP Morgan Climate Report 2022",
    "Mastercard 2022 ESG Report",
    "McKinsey 2022 ESG Full Report",
    "Meta 2023 Sustainability Report",
    "Microsoft 2022 Environmental Sustainability Report",
    "Netflix ESG Report 2022",
    "New Look sustainability report",
    "PayPal Global Impact Report 2023",
    "Qantas 2023 Sustainability Report",
    "Rio Tinto Climate Change Report 2023",
    "Ryanair 2022 Sustainability Report",
    "Sony Sustainability Report 2023",
    "Starbucks Environmental & Social Impact Report 2022",
    "Suncor Sustainability Report 2023",
    "University of Oxford 2022 Sustainability Report",
    "Veolia ESG Report 2023",
    "Walmart ESG Highlights 2023",
    "Westpac 2023 climate report",
    "Woolworths Group 2023 Sustainability Report"
]

SKIP_WORDS = [
            "the",
            "this",
            "these",
            "those",
            "that",
            "one",
            "two",
            "a",
            "an",
            "his",
            "her",
            "many",
            "they",
            "their",
            "et al",
            "some",
            "such",
            "its",
            "all",
            "each",
            "both",
            "our",
            "we",
            "us",
            "our",
            "you",
            "your",
            "my",
            "mine",
            "he",
            "she",
            "it",
            "I",
            "me",
            "who",
            "whom",
            "whose",
            "which",
            "what",
            "any",
            "few",
            "several",
            "more",
            "most",
            "other",
            "another",
            "much",
            "him",
            "hers",
            "ours",
            "yours",
            "theirs",
            "there",
            "here",
            "and",
            "or",
            "nor",
            "but",
            "if",
            "while",
            "because",
            "to",
            "from",
            "of",
            "for",
            "with",
            "on",
            "at",
            "by",
            "about",
            "as",
            "in",
            "into",
            "upon",
            "like",
            "through",
            "over",
            "under",
            "between",
            "since",
            "until",
            "dataset",
        ]

SKIP_CHARS = [
            ".",
            "/",
            "%",
            "(",
            "fig",
            "table",
        ]

DELIMITERS = {
    "section_delimiter": "-",
    "tuple_delimiter": "<|>",
    "completion_delimiter": "<|COMPLETE|>",
    "record_delimiter": "##",
}

ABBREVIATIONS = {
    'ghg': 'greenhouse gases',
    'co2': 'carbon dioxide',
    'co2e': 'carbon dioxide equivalent',
    'mtco2e': 'metric tons carbon dioxide equivalent',
    'mtcoze': 'metric tons carbon dioxide equivalent',
    'mwh': 'megawatt-hour',
    'kwh': 'kilowatt-hour',
    'ch4': 'methane',
    'n2o': 'nitrous oxide',
    'esg': 'environmental social governance',
    'ifrs': 'international financial reporting standards',
    'tcfd': 'task force on climate related financial disclosures',
    'sasb': 'sustainability accounting standards board',
    'esrs': 'european sustainability reporting standard',
    'cdp': 'carbon disclosure project',
    'sbti': 'science based targets initiative',
    'gri': 'global reporting initiative',
    'cop26': '26th united nations climate change conference',
    'un': 'united nations',
    'eu': 'european union',
    'us': 'united states of america',
    'epa': 'environment protection agency',
    'defra': 'department for environment, food and rural affairs',
    'ceo': 'chief executive officer',
    'cfo': 'chief financial officer',
    'ev': 'electical vehicle',
    'evs': 'electrical vehicle',
    'ngo': 'non governmental organization',
    'erm': 'enterprise risk management',
    'saf': 'sustainable aviation fuel',
    'ipcc': 'intergovernmental panel on climate change',
    'recs': 'renewable energy certificates',
    'ppas': 'power purchase agreements',
    'pue': 'power usage effectiveness',
    'aws': 'amazon web services'
}   

ORG_SUFFIXES = {
    'inc', 'incorporated', 'corp', 'corporation', 'ltd', 'limited',
    'llc', 'co', 'company', 'plc', 'gmbh', 'ag', 'sa', 'nv'
}

SUSTAINABLE_QA_REPORTS = [
    'manz_ag',
    'westwing_group_se',
    'united_internet_ag',
    'freenet_ag',
    'takkt_ag_sustain_report',
    'sgl_carbon_se',
    'scout24_se',
    'bechtle_ag',
    'amadeus_fire_ag',
    'zumtobel_group_ag',
    'uniper_se_na_o.n',
    'volkswagen_ag_st',
    'merck_kgaa',
    'porr_ag',
    'hapag_lloyd_ag',
    'sma_solar_technology_ag',
    '1_1_ag',
    'takkt_ag_annual_report',
    'palfinger_ag',
    'washtec_ag',
    'andritz',
    'deutsche_börse_ag',
    'teamviewer_se',
    'q_beyond_ag',
    'atoss_software_se',
    'ca_immobilien_anlagen_ag',
    'amag',
    'stratec_se',
    'lenzing_ag',
    'addiko-bank-ag-sustainability-report-2023',
    'ionos_group_se',
    'uniqa_insurance_group_ag',
    'evonik_industries_ag',
    'kion_group_ag',
    'baywa_ag_vna',
    'syzygy_ag',
    'frequentis_ag',
    'commerzbank_ag',
    'traton_se',
    'suss_microtec_se',
    'polytec_holding_ag',
    'eckert_ziegler_se',
    'flughafen_wien_ag',
    'vossloh_ag',
    'wienerberger_ag',
    'max_automation_se_na_o_n',
    'warimpex_finanz_und_bet_ag',
    'zalando_se',
    'wacker_chemie_ag',
    'mlp_se',
    'schoeller_bleckmann_ag',
    'siltronic_ag',
    'viscom_se',
    'mtu_aero_engines_ag',
    'technotrans_se',
    'agrana',
    'immofinanz_ag',
    'vonovia_se_sustainability_report',
    'indus_holding_ag',
    'tag_immobilien_ag',
    'vonovia_se_annual_report'
    ]